export const mockAGMs = [
  {
    id: "agm-1",
    strataplanId: "1",
    date: "2026-08-15",
    location: "Building Common Room, Level 1, 123 Southbank Blvd",
    status: "scheduled",
    quorumRequired: 12,
    quorumAchieved: null,
    agenda: [
      { id: "a1", order: 1, title: "Welcome and apologies" },
      { id: "a2", order: 2, title: "Confirmation of previous minutes — AGM 2025" },
      { id: "a3", order: 3, title: "Financial statements — FY2025-26" },
      { id: "a4", order: 4, title: "Insurance renewal approval", motionId: "m1" },
      { id: "a5", order: 5, title: "Budget approval FY2026-27", motionId: "m2" },
      { id: "a6", order: 6, title: "Election of committee members" },
      { id: "a7", order: 7, title: "Capital works plan review", motionId: "m3" },
      { id: "a8", order: 8, title: "General business" },
    ],
    motions: [
      { id: "m1", title: "Insurance renewal with QBE", description: "That the OC approve renewal of building insurance with QBE Insurance Australia for $28,500 for the period 1 September 2026 to 31 August 2027.", votesFor: null, votesAgainst: null, votesAbstain: null, passed: null, entitlementFor: null, entitlementAgainst: null },
      { id: "m2", title: "Budget approval FY2026-27", description: "That the OC approve the proposed budget of $74,000 for the financial year commencing 1 July 2026, including admin fund budget of $52,000 and capital works fund budget of $22,000.", votesFor: null, votesAgainst: null, votesAbstain: null, passed: null, entitlementFor: null, entitlementAgainst: null },
      { id: "m3", title: "Capital works levy increase", description: "That the OC approve an increase in the capital works fund levy from $400 to $438.50 per lot per quarter, effective 1 October 2026, to address projected fund shortfall.", votesFor: null, votesAgainst: null, votesAbstain: null, passed: null, entitlementFor: null, entitlementAgainst: null },
    ],
    proxies: [
      { lotId: "l1-6", ownerId: "o6", proxyTo: "James Chen", receivedDate: "2026-08-10", valid: true },
      { lotId: "l1-9", ownerId: "o8", proxyTo: "Sarah Mitchell", receivedDate: "2026-08-12", valid: true },
      { lotId: "l1-10", ownerId: "o9", proxyTo: "Emma Thompson", receivedDate: "2026-08-11", valid: true },
    ],
  },
  {
    id: "agm-2",
    strataplanId: "2",
    date: "2025-09-18",
    location: "Virtual — Zoom Meeting",
    status: "completed",
    quorumRequired: 3,
    quorumAchieved: 10,
    agenda: [
      { id: "b1", order: 1, title: "Welcome and apologies" },
      { id: "b2", order: 2, title: "Confirmation of previous minutes" },
      { id: "b3", order: 3, title: "Financial statements FY2024-25" },
      { id: "b4", order: 4, title: "Insurance renewal approval", motionId: "m4" },
      { id: "b5", order: 5, title: "Budget approval FY2025-26", motionId: "m5" },
      { id: "b6", order: 6, title: "Special levy motion", motionId: "m6" },
      { id: "b7", order: 7, title: "General business" },
    ],
    motions: [
      { id: "m4", title: "Insurance approval — Allianz", description: "That the OC approve renewal of building insurance with Allianz for $12,000.", votesFor: 8, votesAgainst: 2, votesAbstain: 0, passed: true, entitlementFor: 156, entitlementAgainst: 40 },
      { id: "m5", title: "Budget approval FY2025-26", description: "That the OC approve the proposed budget of $32,000.", votesFor: 10, votesAgainst: 1, votesAbstain: 1, passed: true, entitlementFor: 185, entitlementAgainst: 22 },
      { id: "m6", title: "Special levy for lift upgrade", description: "That the OC approve a special levy of $2,500 per lot to fund the lift modernisation project.", votesFor: 4, votesAgainst: 7, votesAbstain: 1, passed: false, entitlementFor: 82, entitlementAgainst: 130 },
    ],
    proxies: [],
  },
];
