export const mockComplaints = [
  {
    id: "cmp-001",
    strataplanId: "1",
    lotId: "l1-12",
    ownerId: "o4",
    category: "noise",
    title: "Persistent late-night noise from Lot 11",
    description: "Owner of Lot 12 reports repeated disturbance from Lot 11 between 11pm and 2am on weekends. Music audible through walls. Has occurred at least 6 times in the past month.",
    submittedDate: "2026-06-12",
    status: "in-progress",
    priority: "high",
    managerResponse: "Formal notice issued to Lot 11 owner under Bylaw 12. Will monitor for recurrence.",
    responseDate: "2026-06-14",
    dueDate: "2026-06-26",
    isOverdue: false,
  },
  {
    id: "cmp-002",
    strataplanId: "1",
    lotId: "l1-7",
    ownerId: "o1",
    category: "financial",
    title: "Commission not disclosed — contractor referral",
    description: "I noticed a referral commission of $200 was charged on the June cleaning invoice. This was not disclosed to the OC committee before engagement as required under the Owners Corporations Act 2006. Requesting full disclosure register.",
    submittedDate: "2026-06-08",
    status: "resolved",
    priority: "high",
    managerResponse: "Apologies for the oversight. Commission has been recorded in the disclosure register and added to the next committee meeting agenda. Full register available in the documents section.",
    responseDate: "2026-06-10",
    dueDate: "2026-06-22",
    isOverdue: false,
  },
  {
    id: "cmp-003",
    strataplanId: "1",
    lotId: "l1-3",
    ownerId: "o2",
    category: "maintenance",
    title: "Water leak from Level 3 common area",
    description: "Water ingress from the Level 3 corridor into Lot 201 ceiling. Started after recent heavy rain. Damage to plaster and carpet visible. Urgent repair needed.",
    submittedDate: "2026-06-01",
    status: "open",
    priority: "high",
    managerResponse: null,
    responseDate: null,
    dueDate: "2026-06-15",
    isOverdue: true,
  },
  {
    id: "cmp-004",
    strataplanId: "2",
    lotId: "l2-3",
    ownerId: "o11",
    category: "governance",
    title: "AGM minutes not circulated within 30 days",
    description: "The 2025 AGM minutes have not been circulated to lot owners within the 30-day statutory period. It has now been 45 days. Please provide minutes immediately.",
    submittedDate: "2026-05-20",
    status: "resolved",
    priority: "medium",
    managerResponse: "Minutes have been finalised and distributed to all owners via email. Available in the documents section of the owner portal.",
    responseDate: "2026-05-23",
    dueDate: "2026-06-03",
    isOverdue: false,
  },
  {
    id: "cmp-005",
    strataplanId: "3",
    lotId: "l3-3",
    ownerId: "o14",
    category: "bylaw",
    title: "Unauthorised pet in common areas",
    description: "Owner of Lot 1 is bringing a large dog into the pool area and common garden, in breach of Bylaw 9 (No Pets in Common Property). Request formal warning be issued.",
    submittedDate: "2026-06-10",
    status: "open",
    priority: "medium",
    managerResponse: null,
    responseDate: null,
    dueDate: "2026-06-24",
    isOverdue: false,
  },
];
