export const mockExpenses = [
  { id: "exp-001", strataplanId: "1", date: "2026-06-05", vendor: "CleanPro Services", amount: 2200, category: "cleaning", fund: "admin", description: "Monthly common area cleaning — June 2026", status: "approved", receiptUrl: null, approvedBy: "Sarah Johnson", approvedDate: "2026-06-06", isCommissionRelated: true, commissionAmount: 200, contractorId: "c1" },
  { id: "exp-002", strataplanId: "1", date: "2026-06-01", vendor: "QBE Insurance", amount: 28500, category: "insurance", fund: "admin", description: "Annual building and public liability insurance renewal", status: "approved", receiptUrl: null, approvedBy: "Sarah Johnson", approvedDate: "2026-06-01", isCommissionRelated: false, commissionAmount: null, contractorId: null },
  { id: "exp-003", strataplanId: "1", date: "2026-05-28", vendor: "Green Thumb Landscaping", amount: 950, category: "gardening", fund: "admin", description: "Garden maintenance and hedge trimming — May 2026", status: "approved", receiptUrl: null, approvedBy: "Sarah Johnson", approvedDate: "2026-05-29", isCommissionRelated: true, commissionAmount: 100, contractorId: "c2" },
  { id: "exp-004", strataplanId: "1", date: "2026-05-15", vendor: "Elite Strata Management", amount: 3500, category: "management-fee", fund: "admin", description: "Monthly management fee — May 2026", status: "approved", receiptUrl: null, approvedBy: "OC Committee", approvedDate: "2026-05-15", isCommissionRelated: false, commissionAmount: null, contractorId: null },
  { id: "exp-005", strataplanId: "1", date: "2026-05-10", vendor: "City Power VIC", amount: 1240, category: "utilities", fund: "admin", description: "Common area electricity — April billing cycle", status: "approved", receiptUrl: null, approvedBy: "Sarah Johnson", approvedDate: "2026-05-11", isCommissionRelated: false, commissionAmount: null, contractorId: null },
  { id: "exp-006", strataplanId: "1", date: "2026-04-22", vendor: "Fix-It Fast Maintenance", amount: 1850, category: "maintenance", fund: "admin", description: "Lobby door motor replacement and intercom repair", status: "approved", receiptUrl: null, approvedBy: "Sarah Johnson", approvedDate: "2026-04-23", isCommissionRelated: false, commissionAmount: null, contractorId: "c3" },
  { id: "exp-007", strataplanId: "1", date: "2026-04-15", vendor: "Elite Strata Management", amount: 3500, category: "management-fee", fund: "admin", description: "Monthly management fee — April 2026", status: "approved", receiptUrl: null, approvedBy: "OC Committee", approvedDate: "2026-04-15", isCommissionRelated: false, commissionAmount: null, contractorId: null },
  { id: "exp-008", strataplanId: "1", date: "2026-06-10", vendor: "SkyHigh Window Cleaning", amount: 1800, category: "cleaning", fund: "admin", description: "External window cleaning — full building", status: "pending", receiptUrl: null, approvedBy: null, approvedDate: null, isCommissionRelated: false, commissionAmount: null, contractorId: "c4" },
  { id: "exp-009", strataplanId: "1", date: "2026-06-08", vendor: "Apex Plumbing Solutions", amount: 3200, category: "maintenance", fund: "capital-works", description: "Roof drainage repair and waterproofing — Level 8", status: "pending", receiptUrl: null, approvedBy: null, approvedDate: null, isCommissionRelated: false, commissionAmount: null, contractorId: "c5" },
  { id: "exp-010", strataplanId: "1", date: "2026-03-20", vendor: "Maddocks Lawyers", amount: 4500, category: "legal", fund: "admin", description: "Legal advice — OC dispute resolution and bylaw review", status: "approved", receiptUrl: null, approvedBy: "OC Committee", approvedDate: "2026-03-22", isCommissionRelated: false, commissionAmount: null, contractorId: null },
  // Collins St
  { id: "exp-011", strataplanId: "2", date: "2026-06-03", vendor: "MelbClean Commercial", amount: 800, category: "cleaning", fund: "admin", description: "Fortnightly common area cleaning — June", status: "approved", receiptUrl: null, approvedBy: "Sarah Johnson", approvedDate: "2026-06-04", isCommissionRelated: false, commissionAmount: null, contractorId: "c6" },
  { id: "exp-012", strataplanId: "2", date: "2026-06-01", vendor: "Allianz Insurance", amount: 12000, category: "insurance", fund: "admin", description: "Annual strata insurance renewal — Collins St", status: "approved", receiptUrl: null, approvedBy: "Sarah Johnson", approvedDate: "2026-06-01", isCommissionRelated: false, commissionAmount: null, contractorId: null },
  { id: "exp-013", strataplanId: "2", date: "2026-05-15", vendor: "Elite Strata Management", amount: 1500, category: "management-fee", fund: "admin", description: "Monthly management fee — May 2026", status: "approved", receiptUrl: null, approvedBy: "OC Committee", approvedDate: "2026-05-15", isCommissionRelated: false, commissionAmount: null, contractorId: null },
  { id: "exp-014", strataplanId: "2", date: "2026-04-18", vendor: "Lift Solutions Vic", amount: 18000, category: "maintenance", fund: "capital-works", description: "Lift service contract — annual + emergency callout", status: "approved", receiptUrl: null, approvedBy: "OC Committee", approvedDate: "2026-04-20", isCommissionRelated: false, commissionAmount: null, contractorId: "c7" },
  { id: "exp-015", strataplanId: "2", date: "2026-05-25", vendor: "Origin Energy", amount: 680, category: "utilities", fund: "admin", description: "Common area gas and electricity — May billing", status: "approved", receiptUrl: null, approvedBy: "Sarah Johnson", approvedDate: "2026-05-26", isCommissionRelated: false, commissionAmount: null, contractorId: null },
  // St Kilda
  { id: "exp-016", strataplanId: "3", date: "2026-06-02", vendor: "Beach Clean Co", amount: 450, category: "cleaning", fund: "admin", description: "Monthly cleaning — June 2026", status: "approved", receiptUrl: null, approvedBy: "Sarah Johnson", approvedDate: "2026-06-03", isCommissionRelated: false, commissionAmount: null, contractorId: "c8" },
  { id: "exp-017", strataplanId: "3", date: "2026-05-20", vendor: "Coastal Gardens", amount: 380, category: "gardening", fund: "admin", description: "Garden tidy and pool area landscaping", status: "approved", receiptUrl: null, approvedBy: "Sarah Johnson", approvedDate: "2026-05-21", isCommissionRelated: false, commissionAmount: null, contractorId: "c9" },
  { id: "exp-018", strataplanId: "3", date: "2026-05-15", vendor: "Elite Strata Management", amount: 900, category: "management-fee", fund: "admin", description: "Monthly management fee — May 2026", status: "approved", receiptUrl: null, approvedBy: "OC Committee", approvedDate: "2026-05-15", isCommissionRelated: false, commissionAmount: null, contractorId: null },
  { id: "exp-019", strataplanId: "3", date: "2026-04-10", vendor: "Pool Tech VIC", amount: 2800, category: "maintenance", fund: "capital-works", description: "Pool pump replacement and chemical system upgrade", status: "approved", receiptUrl: null, approvedBy: "OC Committee", approvedDate: "2026-04-12", isCommissionRelated: true, commissionAmount: 280, contractorId: "c10" },
  { id: "exp-020", strataplanId: "3", date: "2026-06-09", vendor: "Fire Safety Vic", amount: 1200, category: "maintenance", fund: "admin", description: "Annual fire safety inspection and certification", status: "pending", receiptUrl: null, approvedBy: null, approvedDate: null, isCommissionRelated: false, commissionAmount: null, contractorId: "c11" },
];
