export const mockOwners = [
  {
    id: "o1",
    firstName: "James",
    lastName: "Chen",
    email: "james.chen@email.com",
    phone: "0412 345 678",
    address: "Lot 7, 123 Southbank Blvd, Melbourne VIC 3006",
    company: null,
    lots: ["l1-7"],
    portalAccess: true,
  },
  {
    id: "o2",
    firstName: "Sarah",
    lastName: "Mitchell",
    email: "sarah.mitchell@outlook.com",
    phone: "0423 456 789",
    address: "12 Elwood Ave, Elwood VIC 3184",
    company: null,
    lots: ["l1-3", "l1-4"],
    portalAccess: true,
  },
  {
    id: "o3",
    firstName: "Priya",
    lastName: "Sharma",
    email: "priya.sharma@gmail.com",
    phone: "0434 567 890",
    address: "45 St Georges Rd, Toorak VIC 3142",
    company: "Sharma Investments Pty Ltd",
    lots: ["l1-1"],
    portalAccess: true,
  },
  {
    id: "o4",
    firstName: "Michael",
    lastName: "O'Brien",
    email: "m.obrien@bigpond.com",
    phone: "0445 678 901",
    address: "7 Chapel St, Windsor VIC 3181",
    company: null,
    lots: ["l1-12"],
    portalAccess: false,
  },
  {
    id: "o5",
    firstName: "Nguyen",
    lastName: "Thi Lan",
    email: "nguyen.thilan@hotmail.com",
    phone: "0456 789 012",
    address: "Lot 2, 123 Southbank Blvd, Melbourne VIC 3006",
    company: null,
    lots: ["l1-2"],
    portalAccess: true,
  },
  {
    id: "o6",
    firstName: "Emma",
    lastName: "Thompson",
    email: "emma.thompson@email.com",
    phone: "0467 890 123",
    address: "23 Acland St, St Kilda VIC 3182",
    company: "Thompson Property Group",
    lots: ["l1-5", "l1-6"],
    portalAccess: true,
  },
  {
    id: "o7",
    firstName: "David",
    lastName: "Kowalski",
    email: "d.kowalski@gmail.com",
    phone: "0478 901 234",
    address: "89 Hawthorn Rd, Caulfield VIC 3162",
    company: null,
    lots: ["l1-8"],
    portalAccess: true,
  },
  {
    id: "o8",
    firstName: "Aisha",
    lastName: "Rahman",
    email: "aisha.rahman@outlook.com",
    phone: "0489 012 345",
    address: "15 Park St, South Yarra VIC 3141",
    company: null,
    lots: ["l1-9"],
    portalAccess: false,
  },
  {
    id: "o9",
    firstName: "Thomas",
    lastName: "Nguyen",
    email: "t.nguyen@bigpond.com.au",
    phone: "0490 123 456",
    address: "6 Grey St, St Kilda VIC 3182",
    company: null,
    lots: ["l1-10"],
    portalAccess: true,
  },
  {
    id: "o10",
    firstName: "Lisa",
    lastName: "Wang",
    email: "lisa.wang@email.com.au",
    phone: "0401 234 567",
    address: "102 Flinders St, Melbourne VIC 3000",
    company: "LW Property Holdings",
    lots: ["l2-1", "l2-2"],
    portalAccess: true,
  },
  {
    id: "o11",
    firstName: "Robert",
    lastName: "Fitzgerald",
    email: "robert.fitzgerald@hotmail.com",
    phone: "0402 345 678",
    address: "77 Punt Rd, Richmond VIC 3121",
    company: null,
    lots: ["l2-3"],
    portalAccess: true,
  },
  {
    id: "o12",
    firstName: "Mei",
    lastName: "Tanaka",
    email: "mei.tanaka@gmail.com",
    phone: "0403 456 789",
    address: "34 Queens Rd, Melbourne VIC 3004",
    company: null,
    lots: ["l2-4"],
    portalAccess: false,
  },
  {
    id: "o13",
    firstName: "John",
    lastName: "Papadopoulos",
    email: "j.papadopoulos@outlook.com",
    phone: "0404 567 890",
    address: "11 Balaclava Rd, St Kilda East VIC 3183",
    company: "Papadopoulos Real Estate",
    lots: ["l3-1", "l3-2"],
    portalAccess: true,
  },
  {
    id: "o14",
    firstName: "Amelia",
    lastName: "Johnson",
    email: "amelia.johnson@email.com",
    phone: "0405 678 901",
    address: "28 Acland St, St Kilda VIC 3182",
    company: null,
    lots: ["l3-3"],
    portalAccess: true,
  },
  {
    id: "o15",
    firstName: "Kevin",
    lastName: "Pham",
    email: "kevin.pham@gmail.com",
    phone: "0406 789 012",
    address: "56 Wellington St, Collingwood VIC 3066",
    company: null,
    lots: ["l1-11", "l3-4"],
    portalAccess: true,
  },
];
