export const mockLots = [
  // Southbank Residences (plan 1) — 12 lots shown
  { id: "l1-1", strataplanId: "1", lotNumber: "Lot 1", unitNumber: "101", floor: 1, type: "apartment", entitlementUnits: 12, ownerId: "o3", status: "occupied" },
  { id: "l1-2", strataplanId: "1", lotNumber: "Lot 2", unitNumber: "102", floor: 1, type: "apartment", entitlementUnits: 10, ownerId: "o5", status: "occupied" },
  { id: "l1-3", strataplanId: "1", lotNumber: "Lot 3", unitNumber: "201", floor: 2, type: "apartment", entitlementUnits: 14, ownerId: "o2", status: "occupied" },
  { id: "l1-4", strataplanId: "1", lotNumber: "Lot 4", unitNumber: "202", floor: 2, type: "apartment", entitlementUnits: 14, ownerId: "o2", status: "occupied" },
  { id: "l1-5", strataplanId: "1", lotNumber: "Lot 5", unitNumber: "301", floor: 3, type: "apartment", entitlementUnits: 16, ownerId: "o6", status: "occupied" },
  { id: "l1-6", strataplanId: "1", lotNumber: "Lot 6", unitNumber: "302", floor: 3, type: "apartment", entitlementUnits: 16, ownerId: "o6", status: "vacant" },
  { id: "l1-7", strataplanId: "1", lotNumber: "Lot 7", unitNumber: "714", floor: 7, type: "apartment", entitlementUnits: 15, ownerId: "o1", status: "occupied" },
  { id: "l1-8", strataplanId: "1", lotNumber: "Lot 8", unitNumber: "501", floor: 5, type: "apartment", entitlementUnits: 18, ownerId: "o7", status: "occupied" },
  { id: "l1-9", strataplanId: "1", lotNumber: "Lot 9", unitNumber: "601", floor: 6, type: "apartment", entitlementUnits: 20, ownerId: "o8", status: "occupied" },
  { id: "l1-10", strataplanId: "1", lotNumber: "Lot 10", unitNumber: "B01", floor: -1, type: "carpark", entitlementUnits: 4, ownerId: "o9", status: "occupied" },
  { id: "l1-11", strataplanId: "1", lotNumber: "Lot 11", unitNumber: "S01", floor: -2, type: "storage", entitlementUnits: 2, ownerId: "o15", status: "occupied" },
  { id: "l1-12", strataplanId: "1", lotNumber: "Lot 12", unitNumber: "801", floor: 8, type: "apartment", entitlementUnits: 25, ownerId: "o4", status: "occupied" },
  // Collins St Apartments (plan 2) — 10 lots
  { id: "l2-1", strataplanId: "2", lotNumber: "Lot 1", unitNumber: "101", floor: 1, type: "apartment", entitlementUnits: 18, ownerId: "o10", status: "occupied" },
  { id: "l2-2", strataplanId: "2", lotNumber: "Lot 2", unitNumber: "102", floor: 1, type: "apartment", entitlementUnits: 18, ownerId: "o10", status: "occupied" },
  { id: "l2-3", strataplanId: "2", lotNumber: "Lot 3", unitNumber: "201", floor: 2, type: "apartment", entitlementUnits: 22, ownerId: "o11", status: "occupied" },
  { id: "l2-4", strataplanId: "2", lotNumber: "Lot 4", unitNumber: "202", floor: 2, type: "apartment", entitlementUnits: 20, ownerId: "o12", status: "occupied" },
  { id: "l2-5", strataplanId: "2", lotNumber: "Lot 5", unitNumber: "301", floor: 3, type: "apartment", entitlementUnits: 24, ownerId: null, status: "vacant" },
  { id: "l2-6", strataplanId: "2", lotNumber: "Lot 6", unitNumber: "302", floor: 3, type: "apartment", entitlementUnits: 22, ownerId: null, status: "vacant" },
  { id: "l2-7", strataplanId: "2", lotNumber: "Lot 7", unitNumber: "B01", floor: -1, type: "carpark", entitlementUnits: 5, ownerId: null, status: "occupied" },
  { id: "l2-8", strataplanId: "2", lotNumber: "Lot 8", unitNumber: "B02", floor: -1, type: "carpark", entitlementUnits: 5, ownerId: null, status: "occupied" },
  { id: "l2-9", strataplanId: "2", lotNumber: "Lot 9", unitNumber: "401", floor: 4, type: "apartment", entitlementUnits: 25, ownerId: null, status: "occupied" },
  { id: "l2-10", strataplanId: "2", lotNumber: "Lot 10", unitNumber: "S01", floor: -2, type: "storage", entitlementUnits: 3, ownerId: null, status: "occupied" },
  // St Kilda Beach Villas (plan 3) — 8 lots
  { id: "l3-1", strataplanId: "3", lotNumber: "Lot 1", unitNumber: "1", floor: 1, type: "apartment", entitlementUnits: 20, ownerId: "o13", status: "occupied" },
  { id: "l3-2", strataplanId: "3", lotNumber: "Lot 2", unitNumber: "2", floor: 1, type: "apartment", entitlementUnits: 20, ownerId: "o13", status: "occupied" },
  { id: "l3-3", strataplanId: "3", lotNumber: "Lot 3", unitNumber: "3", floor: 2, type: "apartment", entitlementUnits: 18, ownerId: "o14", status: "occupied" },
  { id: "l3-4", strataplanId: "3", lotNumber: "Lot 4", unitNumber: "4", floor: 2, type: "apartment", entitlementUnits: 18, ownerId: "o15", status: "occupied" },
  { id: "l3-5", strataplanId: "3", lotNumber: "Lot 5", unitNumber: "5", floor: 3, type: "apartment", entitlementUnits: 15, ownerId: null, status: "vacant" },
  { id: "l3-6", strataplanId: "3", lotNumber: "Lot 6", unitNumber: "6", floor: 3, type: "apartment", entitlementUnits: 15, ownerId: null, status: "occupied" },
  { id: "l3-7", strataplanId: "3", lotNumber: "Lot 7", unitNumber: "B1", floor: -1, type: "carpark", entitlementUnits: 4, ownerId: null, status: "occupied" },
  { id: "l3-8", strataplanId: "3", lotNumber: "Lot 8", unitNumber: "B2", floor: -1, type: "carpark", entitlementUnits: 4, ownerId: null, status: "occupied" },
];
